### ISSUE TITLE
How to Import this?

### ISSUE THREAD

**Issue by firdarinoa** [LiewJunTung/pin_code_text_field#4]
I'm new to flutter and I want to ask how to import this? I've add this to my pubspec:
```
dependencies:
  flutter:
    sdk: flutter
  pin_code_text_field:
    git:
      url: git://github.com/LiewJunTung/pin_code_text_field.git
```
but I don't know how to import it and use PinCodeEntryField. Does anyone know how?
